# Generated by Django 4.0.1 on 2022-01-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spool',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='spool',
            name='image',
        ),
        migrations.RemoveField(
            model_name='spool',
            name='summary',
        ),
        migrations.AddField(
            model_name='spool',
            name='date',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='name',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
    ]
