# Generated by Django 4.0.1 on 2022-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spools', '0002_alter_spool_options_remove_spool_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spool',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
