# Generated by Django 4.0.1 on 2022-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spools', '0003_alter_spool_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spool',
            options={'ordering': ('tag',)},
        ),
        migrations.RenameField(
            model_name='spool',
            old_name='date',
            new_name='spooled_date',
        ),
        migrations.RenameField(
            model_name='spool',
            old_name='name',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='spool',
            name='EL',
            field=models.CharField(default='NA', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='PL',
            field=models.CharField(default='NA', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='area',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='comments',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='description',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='fab_completed',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='fab_shop',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='installed',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='insulation_blocks',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='level',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='on_site',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spool',
            name='released_shop',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
    ]
