# Generated by Django 4.0.1 on 2022-01-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spools', '0004_alter_spool_options_rename_date_spool_spooled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spool',
            name='upload',
            field=models.FileField(default='na', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
