# Generated by Django 4.0.1 on 2022-01-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spools', '0006_remove_spool_upload_spool_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spool',
            name='drawing',
        ),
    ]
